[profile.default]
src = "src"
out = "artifacts"
libs = ["dependencies"]
remappings = [
    'src/=src',
    '@forge-std/=dependencies/forge-std-1.9.1',
]

[dependencies]
forge-std = "1.9.1"
"@openzeppelin-contracts" = "5.0.2"



# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
